jwt:
  secret: 6Dpo82kL8NbtMgqrnfQhNqiG6adnrTECd/69pvAmtsA=

spring:
  data:
    mongodb:
      uri: mongodb+srv://ervishalpathak:Ervishal7603@cluster0.ub7yd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: BlogSopt

  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**




